### ISSUE TITLE
about torch.int

### ISSUE THREAD

**Issue by MTandHJ** [thu-ml/low-bit-optimizers#8]
Hi,

Thanks for your nice work! I notice that `.to(torch.int)` is used in `xxx_quant`, but `torch.int` is the same to `torch.int32`. Could memory reduction can be observed in practice?

Thanks.

**Comment by Bingrui-Li** [comment]
Hi, 

Thank you for your question. Only calling `real_nonlinear_quant` is real quantization. The use of `torch.int` is just for simulation.
